### ISSUE TITLE
LF4_100 download original submissions and corrected versions as ZIP

### ISSUE THREAD

**Issue by hedtke** [ostepu/system#14]
- es kann nur die zu korrigierende ZIP-Datei mit den Einsendungen der Studenten geladen
werden!
- DB: Submission → F_id_file !
- DBL: DBSubmission!
- FS: FSZip

**Comment by tilluhlig** [comment]
Es ist möglich, im Korrekturassistenten eine Zusammenstellung aller Einsendungen und Korrekturen herunterzuladen. (dabei kann diese Auswahl auch auf einen bestimmten Korrekturstatus oder Kontrolleur beschränkt werden)
