### ISSUE TITLE
SQaLibur automatisch einrichten

### ISSUE THREAD

**Issue by Garados007** [ostepu/system#304]
Wenn die Plattform neu eingerichtet wird, dann zeigt es im Installationsassistenten immer an, dass SQaLibur nicht gefunden wurde und auch nicht eingerichtet werden kann. Dies sollte behoben werden, damit auch bei einer kompletten Neuinstallation SQaLibur gefunden wird oder der Fehler nicht mehr erscheint.

**Comment by tilluhlig** [comment]
Wenn du den Hinweis nicht mehr erhalten möchtest, dann solltest du das Paket "SQaLibur" abwählen (Installationsassistent). Der Fehler besagt, dass er SQaLibur nicht findet, weil dazu das zugehörige Servlet bereits irgendwo laufen muss.
35deebe2dce40f795747dc8faadb3982f2b80ffc

**Comment by Garados007** [comment]
Da jetzt eine Information beim Packet selbst ist, wie die Installation von SQaLibur zu erfolgen hat und dies nicht durch OSTEPU erfolgt, sehe ich dieses Issue als abgeschlossen.
