### ISSUE TITLE
Oberflächendateien wie CSS und JS minimieren

### ISSUE THREAD

**Issue by Garados007** [ostepu/system#305]
Dazu in `UI/.htaccess` folgendes hinzufügen:
```
RewriteRule ^([a-zA-Z0-9]*)/css/([a-zA-Z0-9]*).css$ Common/getContent.php?type=css&dir=$1&file=$2 [L]
RewriteRule ^([a-zA-Z0-9]*)/js/([a-zA-Z0-9]*).js$ Common/getContent.php?type=js&dir=$1&file=$2 [L]
```

Zusätzlich eine `UI/Common/getContent.php`, die dann die Abfragen verarbeitet und je nach Modus eine komprimierte oder die originale Datei zur Verfügung stellt.

**Comment by Garados007** [comment]
#306

**Comment by tilluhlig** [comment]
Es wurde nun der https://github.com/ostepu/phpwee-php-minifier verwendet, um die CSS und JS Dateien zu minimieren. Er entfernt aber nur minimal Leerzeichen und Zeilenumbrüche (aber wenigstens was).

Dazu werden die Inhalte über die CContent mittels `GET UI/CContent/content/PfadZurDatei` abgerufen, sodass hierbei direkt entschieden werden kann, ob wir Änderungen an den Dateien vornehmen wollen.

Dazu müssen die UI-Seiten jeweils eine Komponentendefinition erhalten, um die Inhalte ihrer /content Ordner bei CContent anmelden zu können.
